// Generated by CoffeeScript 1.10.0
var PEG, gutil, processFile, through, util;

PEG = require("pegjs");

util = require("util");

gutil = require("gulp-util");

through = require("through2");

processFile = function(file, opts) {
  var grammar, parser, source, variable;
  grammar = file.contents.toString("utf8");
  parser = PEG.buildParser(grammar, opts);
  if (typeof opts.exportVar === 'function') {
    variable = opts.exportVar(file.relative);
  } else {
    if (opts.exportVar !== '') {
      variable = opts.exportVar;
    } else {
      variable = file.relative.split('.')[0] + 'parser';
    }
  }
  source = util.format("%s = %s;", variable, parser);
  file.path = gutil.replaceExtension(file.path, ".js");
  file.contents = new Buffer(source);
  return file;
};

module.exports = function(opts) {
  if (opts == null) {
    opts = {};
  }
  if (opts.exportVar == null) {
    opts.exportVar = "module.exports";
  }
  if (opts.output == null) {
    opts.output = "source";
  }
  return through.obj(function(file, enc, cb) {
    var e, error;
    if (file.isStream()) {
      return this.emit("error", gutil.PluginError("gulp-peg", "Streams are not supported!"));
    } else if (file.isBuffer()) {
      try {
        this.push(processFile(file, opts));
        return cb();
      } catch (error) {
        e = error;
        this.emit("error", e);
        return cb();
      }
    } else if (file.isNull()) {
      this.push(file);
      return cb();
    }
  });
};
